### ISSUE TITLE
The plugin does not give any output

### ISSUE THREAD

**Issue by psyguy** [raineszm/obsidian-export-to-tex#17]
Hi,

I am using Obsidian v. 0.10.11 on Windows 10, and the plugin v. 0.0.3 doesn't seem to make any outputs. The clipboard is empty after running the command and no file is saved after attempting to save via `Export to TeX` command.

**P.S.** I could get an output on a very small note without any embedded notes.

**Comment by raineszm** [comment]
Sorry it's not working for you.

Would be able to send me a zipped sample vault containing the notes which are causing problems? Or any minimal collection of notes that doesn't work?

Also, do you get any errors in console?

**Comment by psyguy** [comment]
Hi again,

I'll make that minimal collection.

But in the meantime, what do you mean by errors in the console? Like a notification that appears on top corner of Obsidian? 🤔

**Comment by psyguy** [comment]
By trial and error, I noticed the problem occurs when there is an image (like `![[Pasted image.png]]`) in the embedded note.

**Comment by raineszm** [comment]
> But in the meantime, what do you mean by errors in the console? Like a notification that appears on top corner of Obsidian? 🤔

If you go to the View menu and select Toggle Developer tools there should be a console on the right side of the screen.

**Comment by raineszm** [comment]
> By trial and error, I noticed the problem occurs when there is an image (like `![[Pasted image.png]]`) in the embedded note.

Ah. This makes sense. I'll get on fixing that.

For reference, what behavior do you expect for embedded images? Converting them to an `\includegraphics` call seems most straightforward but you would of course have to move the image file too.

**Comment by psyguy** [comment]
> If you go to the View menu

Sorry if it is too trivial, but cannot find the view menu 🙊 

> Converting them to an \includegraphics call seems most straightforward but you would of course have to move the image file too.

True. It would be good if in `\includegraphic` went the image with its absolute address, so that I can compile the TeX from elsewhere without the need to actually move the image files.

**Comment by raineszm** [comment]
> > If you go to the View menu
> 
> Sorry if it is too trivial, but cannot find the view menu 🙊
> 
I think you should be able to open it with `Ctrl-Shift-I` or `Ctrl-Alt-I`. Sorry I don't have a windows machine.

> > Converting them to an \includegraphics call seems most straightforward but you would of course have to move the image file too.
> 
> True. It would be good if in `\includegraphic` went the image with its absolute address, so that I can compile the TeX from elsewhere without the need to actually move the image files.
I just added the ability to transform into an `\includegraphic` command with the path relative to the vault root, but I'll try to add a setting to use the absolute path to the file.
In a future version I hope to be able to set this options on a per file basis from the frontmatter.

All that aside I can't seem to reproduce the issue yet. Even with an image embed I still get generated tex, so clearly I'm somehow still missing the root of the problem.

**Comment by psyguy** [comment]
Thanks for your swift replies :)

> I think you should be able to open it with `Ctrl-Shift-I`

Ah, I see what you mean.

I made a very small vault ([zipped here](https://gofile.io/d/JvP32X)), and here is the error I get in the console when I want to export `sample note.md` to TeX:

![image](https://user-images.githubusercontent.com/8527082/107430424-6ce76c80-6b25-11eb-905f-fb6afca74fbf.png)

If you remove line 32, there will be no issues in the export.

**Comment by raineszm** [comment]
Perfect! At first glance it looks like the issue is an image embed and a block reference on the same line. I'll try to take a look at it tonight or tomorrow. But that's exactly what I needed.

**Comment by raineszm** [comment]
Version `0.1.0` should fix this issue. If it doesn't let me know and I'll reopen it.

**Comment by psyguy** [comment]
Awesome, thanks a lot!

**Comment by psyguy** [comment]
There is an issue with absolute path and Windows:

Windows paths are by default (?) defined with `\` backslashes, which is not recognized by `\includegraphics`. Changing `\`s to `/` would fix it.

Thanks.
