### ISSUE TITLE
Can't Update: Plugin Id Mismatch

### ISSUE THREAD

**Issue by ndharari** [raineszm/obsidian-export-to-tex#27]
That's all. I think theres some problem with the plugin manisfest but I could be wrong

**Comment by ndharari** [comment]
Update: Obsidian seems to think there is a version 3.0 but I cant install it

**Comment by raineszm** [comment]
I've been working on a new version. Not sure why obsidian picked it up since I haven't made any releases, but I'm cutting a release now.
