### ISSUE TITLE
Inline math being turned into (outdated) display math

### ISSUE THREAD

**Issue by Ellpeck** [raineszm/obsidian-export-to-tex#31]
When creating `$inline math$`, and exporting it to TeX, it gets turned into `$$outdated display math$$`. 

This makes proofs and other text with a lot of inline math look very bad, and double dollar display math is [discouraged in modern LaTeX](https://tex.stackexchange.com/questions/85345/enumeration-of-equations-in-the-double-dollar-math-mode). I assume this is just a conversion/parsing issue though, so it should be an easy fix, I hope.

**Comment by raineszm** [comment]
Interesting. In-line math is being converted to display math? 

Regardless I'll add a toggle for using the raw Tex vs latex displaymath.
